### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yarynam**

### CODE REVIEW

**Comment by Synthia** [comment]
Could someone move me out the this channel?

I keep getting email from federal election channel.

Thanks,

Site

---

发件人: Iaryna notifications@github.com
发送时间: 2015年11月8日 18:06
收件人: j4502/federal_elections
主题: [federal_elections] Develop (#11)

---

You can view, comment on, or merge this pull request online at:

  https://github.com/j4502/federal_elections/pull/11

[https://avatars0.githubusercontent.com/u/12760249?v=3&s=400]https://github.com/j4502/federal_elections/pull/11

Develop by yarynam ・ Pull Request #11 ・ j4502/federal_elections
阅读更多信息...https://github.com/j4502/federal_elections/pull/11

Commit Summary
-   Merge branch 'master' into develop
-   Merge pull request #5 from j4502/master
-   fixing merge
-   Merge pull request #6 from j4502/master
-   Merge branch 'develop' of https://github.com/j4502/federal_elections into develop
-   removing old social icons
-   adding new social icons
-   fixing id/class issues, adds an asset folder and an empty css folder, renames img files to direct to proper folder
-   changes formatting of contact info in footer
-   adds empty css file
-   fixes contact info in footer
-   Merge remote-tracking branch 'origin/develop' into develop
-   Wrong twitter button
-   Delete wrong folder
-   h1 to h2
-   add presidential candidates page
-   Merge remote-tracking branch 'origin/develop' into develop
-   adding links to races navigation
-   Merge branch 'develop' of https://github.com/j4502/federal_elections into develop
-   Presidential Candidates' List
-   Add photos for Pres Candidate
-   Candidate Changes
-   Remove old images
-   Removed H3's
-   Moved text onto images
-   Link new pictures in code
-   Text Move
-   svg icons
-   added nav bar (hopefully)
-   fixed the links for the images
-   changed the div structure in nav panel
-   fixed wrong div
-   Removed Candidates header

File Changes
-   A assets/css/application.csshttps://github.com/j4502/federal_elections/pull/11/files#diff-0 (0)
-   A assets/img/BSanders.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-1 (0)
-   A assets/img/HClinton.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-2 (0)
-   A assets/img/MRubio.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-3 (0)
-   R assets/img/Missourian.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-4 (0)
-   A assets/img/candidates.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-5 (25)
-   A assets/img/facebook.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-6 (0)
-   R assets/img/house_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-7 (0)
-   A assets/img/instagram.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-8 (0)
-   A assets/img/issues.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-9 (20)
-   A assets/img/money.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-10 (24)
-   R assets/img/prez_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-11 (0)
-   R assets/img/senate_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-12 (0)
-   A assets/img/twitter.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-13 (0)
-   A assets/img/vimeo.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-14 (0)
-   A assets/img/youtube.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-15 (0)
-   D img/facebook.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-16 (0)
-   D img/instagram.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-17 (0)
-   D img/twitter.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-18 (0)
-   D img/vimeo.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-19 (0)
-   D img/youtube.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-20 (0)
-   M index.htmlhttps://github.com/j4502/federal_elections/pull/11/files#diff-21 (62)
-   A presidential/candidates.htmlhttps://github.com/j4502/federal_elections/pull/11/files#diff-22 (88)

Patch Links:
-   https://github.com/j4502/federal_elections/pull/11.patch
-   https://github.com/j4502/federal_elections/pull/11.diff

―

**Comment by mlalexander** [comment]
No, we cannot change that. You are getting email because you are watching
our repo: https://github.com/j4502/federal_elections/watchers

Madi Alexander
405.570.3222
madialexander.com
@MadiLAlexander http://twitter.com/MadiLAlexander

**Comment by sarajeanne23** [comment]
This is happening to me too. Please remove me from the channel!

Sara Higginbotham

Missouri School of Journalism

Strategic Communication

On Nov 9, 2015, at 10:06 AM, Site Ma <notifications@github.com<mailto:notifications@github.com>> wrote:

Could someone move me out the this channel?

I keep getting email from federal election channel.

Thanks,

Site

---

发件人: Iaryna <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2015年11月8日 18:06
收件人: j4502/federal_elections
主题: [federal_elections] Develop (#11)

---

You can view, comment on, or merge this pull request online at:

https://github.com/j4502/federal_elections/pull/11

[https://avatars0.githubusercontent.com/u/12760249?v=3&s=400]https://github.com/j4502/federal_elections/pull/11

Develop by yarynam ・ Pull Request #11 ・ j4502/federal_elections
阅读更多信息...https://github.com/j4502/federal_elections/pull/11

Commit Summary
- Merge branch 'master' into develop
- Merge pull request #5 from j4502/master
- fixing merge
- Merge pull request #6 from j4502/master
- Merge branch 'develop' of https://github.com/j4502/federal_elections into develop
- removing old social icons
- adding new social icons
- fixing id/class issues, adds an asset folder and an empty css folder, renames img files to direct to proper folder
- changes formatting of contact info in footer
- adds empty css file
- fixes contact info in footer
- Merge remote-tracking branch 'origin/develop' into develop
- Wrong twitter button
- Delete wrong folder
- h1 to h2
- add presidential candidates page
- Merge remote-tracking branch 'origin/develop' into develop
- adding links to races navigation
- Merge branch 'develop' of https://github.com/j4502/federal_elections into develop
- Presidential Candidates' List
- Add photos for Pres Candidate
- Candidate Changes
- Remove old images
- Removed H3's
- Moved text onto images
- Link new pictures in code
- Text Move
- svg icons
- added nav bar (hopefully)
- fixed the links for the images
- changed the div structure in nav panel
- fixed wrong div
- Removed Candidates header

File Changes
- A assets/css/application.csshttps://github.com/j4502/federal_elections/pull/11/files#diff-0 (0)
- A assets/img/BSanders.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-1 (0)
- A assets/img/HClinton.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-2 (0)
- A assets/img/MRubio.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-3 (0)
- R assets/img/Missourian.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-4 (0)
- A assets/img/candidates.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-5 (25)
- A assets/img/facebook.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-6 (0)
- R assets/img/house_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-7 (0)
- A assets/img/instagram.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-8 (0)
- A assets/img/issues.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-9 (20)
- A assets/img/money.svghttps://github.com/j4502/federal_elections/pull/11/files#diff-10 (24)
- R assets/img/prez_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-11 (0)
- R assets/img/senate_home_menu.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-12 (0)
- A assets/img/twitter.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-13 (0)
- A assets/img/vimeo.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-14 (0)
- A assets/img/youtube.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-15 (0)
- D img/facebook.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-16 (0)
- D img/instagram.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-17 (0)
- D img/twitter.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-18 (0)
- D img/vimeo.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-19 (0)
- D img/youtube.pnghttps://github.com/j4502/federal_elections/pull/11/files#diff-20 (0)
- M index.htmlhttps://github.com/j4502/federal_elections/pull/11/files#diff-21 (62)
- A presidential/candidates.htmlhttps://github.com/j4502/federal_elections/pull/11/files#diff-22 (88)

Patch Links:
- https://github.com/j4502/federal_elections/pull/11.patch
- https://github.com/j4502/federal_elections/pull/11.diff

―

**Comment by mlalexander** [comment]
Again, not something we can fix. You're watching the repo:
https://github.com/j4502/federal_elections/watchers

Madi Alexander
405.570.3222
madialexander.com
@MadiLAlexander http://twitter.com/MadiLAlexander

On Mon, Nov 9, 2015 at 10:12 AM, Sara Higginbotham <notifications@github.com

> wrote:
> 
> This is happening to me too. Please remove me from the channel!
> 
> Sara Higginbotham
> 
> Missouri School of Journalism
> 
> Strategic Communication
> 
> On Nov 9, 2015, at 10:06 AM, Site Ma <notifications@github.com<mailto:

**Pull request closed without merging**
